FROM ppc64le/ubuntu:16.04

#installing dependencies packages
RUN apt update && \
	apt install ipmitool && \
	apt install python2.7 && \
	apt install apache2 && \
	apt install python-pip && \
	apt install git	
